import Image from 'next/image';
import { useState } from 'react';

export default function TipButton() {
  const [isShowTip, setIsShowTip] = useState<boolean>(false);

  return (
    <>
      <div
        className="rounded-full absolute top-[-20] left-[-20]  cursor-pointer"
        onMouseEnter={() => setIsShowTip(!isShowTip)}
        onMouseLeave={() => setIsShowTip(!isShowTip)}
      >
        <Image src={'icons/tip-icon.svg'} alt="tip" width={20} height={20} />
      </div>
      {isShowTip && (
        <div className="absolute max-w-[270px] h-[80px] rounded-2xl text-[10px] border mr-20 text-center p-1 bg-gray-50 z-20">
          A vehicle simulation would be generated by AI to evaluate and
          understand the vehicle’s business impact. The leads can review it
          before launching the vehicle. Pressing the info button reveals this
          information.
        </div>
      )}
    </>
  );
}
