export const availableFonts = [
  'Arial',
  'Helvetica',
  'Georgia',
  'Times New Roman',
  'Trebuchet MS',
  'Verdana',
  'Tahoma',
  'Courier New',
  'Lucida Console',
  'Palatino Linotype',
  'Garamond',
  'Comic Sans MS',
  'Impact',
  'Segoe UI',
  'Roboto',
  'Roboto Slab',
  'Inter',
  'Lato',
  'Open Sans',
  'Poppins',
  'Montserrat',
  'Raleway',
  'Merriweather',
  'PT Sans',
  'Ubuntu',
  'Nunito',
  'Oswald',
  'Fira Sans',
  'Work Sans',
  'Rubik'
].sort();
