import { EfficiencyCharts } from '../vehicle/types';
import { CapacityProps } from '../vehicle/types';

export interface CreateWorkerDto {
  image: string;
  name: string;
  surname: string;
  accuratePosition: string; // Job Title
  shortName: string; // f.i A.J Angelina Jolie
  color: string; // randomly
  isManager: boolean; // if user chose position manager
  email: string;
  password: string;
  position: string;
  timeZone: string; // generate
  phoneNumber: string;
}

export interface WorkerListProps extends CreateWorkerDto {
  id: string;
  capacity: CapacityProps[]; // not related to creation
  status: string; // not related as well
  productInProgress: number;
  vehicleInProgress: number;
  relatedVehicles: string[];
  facilitatorIn: string[];
  efficiencyCharts: EfficiencyCharts;
  relatedProducts: string[];
  isTeamLead?: boolean; // indicates if user is assigned as team lead
  teamLeadBorderColor?: string; // border color for team lead (Designer: #8AD5E7, PM: #E182B5, Engineer: #00A86B)
}

export const mockWorkers: WorkerListProps[] = [
  {
    id: '0',
    relatedProducts: [],
    image: 'Ellipse 5.svg',
    name: 'Angelina',
    surname: 'Jolie',
    accuratePosition: 'Senior Engineer',
    shortName: 'A.J',
    color: '#FF5733',
    isManager: true,
    email: 'angelina.jolie@example.com',
    password: '123123',
    position: 'ENGINEER/QA',
    capacity: [],
    status: 'active',
    timeZone: 'UTC+2',
    productInProgress: 2,
    vehicleInProgress: 1,
    phoneNumber: '+1-555-1234',
    relatedVehicles: [],
    facilitatorIn: [],
    efficiencyCharts: {
      speed: 85,
      efficiency: 90,
      quality: 95,
    },
  },
  {
    id: '1',
    relatedProducts: [],
    image: 'Ellipse 5.svg',
    name: 'John',
    surname: 'Doe',
    accuratePosition: 'QA Specialist',
    shortName: 'J.D',
    color: '#33A1FD',
    isManager: false,
    email: 'test@example.com',
    password: '123123',
    position: 'UI/UX',
    capacity: [{ id: 'c3', vehicleName: 'Driller-Y' }],
    status: 'inactive',
    timeZone: 'UTC+1',
    productInProgress: 1,
    vehicleInProgress: 0,
    phoneNumber: '+1-555-5678',
    relatedVehicles: [],
    facilitatorIn: [],
    efficiencyCharts: {
      speed: 70,
      efficiency: 75,
      quality: 80,
    },
  },
  {
    id: '13',
    relatedProducts: [],
    image: 'Ellipse 5.svg',
    name: 'Aboba',
    surname: 'Doe',
    accuratePosition: 'QA Specialist',
    shortName: 'J.D',
    color: '#33A1FD',
    isManager: false,
    email: 'john.doe@example.com',
    password: '123123',
    position: 'UI/UX',
    capacity: [{ id: 'c3', vehicleName: 'Driller-Y' }],
    status: 'inactive',
    timeZone: 'UTC+1',
    productInProgress: 1,
    vehicleInProgress: 0,
    phoneNumber: '+1-555-5678',
    relatedVehicles: [],
    facilitatorIn: [],
    efficiencyCharts: {
      speed: 70,
      efficiency: 75,
      quality: 80,
    },
  },
  {
    id: '228',
    relatedProducts: [],
    image: 'Ellipse 5.svg',
    name: 'Viktor',
    surname: 'Doe',
    accuratePosition: 'QA Specialist',
    shortName: 'J.D',
    color: '#33A1FD',
    isManager: false,
    email: 'john.doe228@example.com',
    password: '123123',
    position: 'UI/UX',
    capacity: [{ id: 'c3', vehicleName: 'Driller-Y' }],
    status: 'inactive',
    timeZone: 'UTC+1',
    productInProgress: 1,
    vehicleInProgress: 0,
    phoneNumber: '+1-555-5678',
    relatedVehicles: [],
    facilitatorIn: [],
    efficiencyCharts: {
      speed: 70,
      efficiency: 75,
      quality: 80,
    },
  },
  {
    id: '118',
    relatedProducts: [],
    image: 'Ellipse 5.svg',
    name: 'Maximilian',
    surname: 'Doe',
    accuratePosition: 'QA Specialist',
    shortName: 'J.D',
    color: '#33A1FD',
    isManager: false,
    email: 'john.doe118@example.com',
    password: '123123',
    position: 'UI/UX',
    capacity: [{ id: 'c3', vehicleName: 'Driller-Y' }],
    status: 'inactive',
    timeZone: 'UTC+1',
    productInProgress: 1,
    vehicleInProgress: 0,
    phoneNumber: '+1-555-5678',
    relatedVehicles: [],
    facilitatorIn: [],
    efficiencyCharts: {
      speed: 70,
      efficiency: 75,
      quality: 80,
    },
  },
  {
    id: '12',
    relatedProducts: [],
    image: 'Ellipse 5.svg',
    name: 'Igor',
    surname: 'Doe',
    accuratePosition: 'QA Specialist',
    shortName: 'J.D',
    color: '#33A1FD',
    isManager: false,
    email: 'john.doe12@example.com',
    password: '123123',
    position: 'UI/UX',
    capacity: [{ id: 'c3', vehicleName: 'Driller-Y' }],
    status: 'inactive',
    timeZone: 'UTC+1',
    productInProgress: 1,
    vehicleInProgress: 0,
    phoneNumber: '+1-555-5678',
    relatedVehicles: [],
    facilitatorIn: [],
    efficiencyCharts: {
      speed: 70,
      efficiency: 75,
      quality: 80,
    },
  },
  {
    id: '1143',
    relatedProducts: [],
    image: 'Ellipse 5.svg',
    name: 'John',
    surname: 'Doe',
    accuratePosition: 'QA Specialist',
    shortName: 'J.D',
    color: '#33A1FD',
    isManager: false,
    email: 'some@example.com',
    password: '123123',
    position: 'UI/UX',
    capacity: [{ id: 'c3', vehicleName: 'Driller-Y' }],
    status: 'inactive',
    timeZone: 'UTC+1',
    productInProgress: 1,
    vehicleInProgress: 0,
    phoneNumber: '+1-555-5678',
    relatedVehicles: [],
    facilitatorIn: [],
    efficiencyCharts: {
      speed: 70,
      efficiency: 75,
      quality: 80,
    },
  },
  {
    id: '2',
    relatedProducts: [],
    image: 'Ellipse 5.svg',
    name: 'Angelina',
    surname: 'Jolie',
    accuratePosition: 'Senior Engineer',
    shortName: 'A.J',
    color: '#FF5733',
    isManager: true,
    email: 'workflow@example.com',
    password: '123123',
    position: 'PM',
    capacity: [],
    status: 'active',
    timeZone: 'UTC+2',
    productInProgress: 2,
    vehicleInProgress: 1,
    phoneNumber: '+1-555-1234',
    relatedVehicles: [],
    facilitatorIn: [],
    efficiencyCharts: {
      speed: 85,
      efficiency: 90,
      quality: 95,
    },
  },
  {
    id: '11111',
    relatedProducts: [],
    image: 'Ellipse 5.svg',
    name: 'Evelina',
    surname: 'Jolie',
    accuratePosition: 'Senior Engineer',
    shortName: 'A.J',
    color: '#FF5733',
    isManager: true,
    email: 'workflow@example.com',
    password: '123123',
    position: 'PM',
    capacity: [],
    status: 'active',
    timeZone: 'UTC+2',
    productInProgress: 2,
    vehicleInProgress: 1,
    phoneNumber: '+1-555-1234',
    relatedVehicles: [],
    facilitatorIn: [],
    efficiencyCharts: {
      speed: 85,
      efficiency: 90,
      quality: 95,
    },
  },
];
