export const testComments = [
  {
    avatarUrl: '',
    nickname: 'john_doe',
    title: 'Great Service!',
    body: 'I had an amazing experience with the workshop. The staff were very professional and quick!',
    time: '2025-06-04 10:15 AM',
    id: 1,
  },
  {
    avatarUrl: '',
    nickname: 'jane_smith',
    title: 'Highly recommend!',
    body: 'The job was done perfectly. They handled everything with care and the price was fair.',
    time: '2025-06-04 11:30 AM',
    id: 2,
  },
  {
    avatarUrl: '',
    nickname: 'car_lover',
    title: 'Fast and efficient',
    body: "I didn't have to wait long at all. The work was top-notch, and I got my car back in no time.",
    time: '2025-06-03 03:45 PM',
    id: 3,
  },
  {
    avatarUrl: '',
    nickname: 'mike_92',
    title: 'Not satisfied',
    body: 'The service took way longer than expected. I was disappointed with the overall experience.',
    time: '2025-06-02 09:00 AM',
    id: 4,
  },
  {
    avatarUrl: '',
    nickname: 'emily_w',
    title: 'Will come back for sure',
    body: 'I love how they explain everything in detail before starting any work. Very trustworthy workshop.',
    time: '2025-06-01 01:20 PM',
    id: 5,
  },
  {
    avatarUrl: '',
    nickname: 'alex_k',
    title: 'Very friendly staff',
    body: 'The team here is always so friendly and professional. They treat you like family!',
    time: '2025-05-31 05:10 PM',
    id: 6,
  },
  {
    avatarUrl: '',
    nickname: 'susan_lee',
    title: 'Quality work, fair price',
    body: 'I appreciate the quality work they did on my car. Everything was explained well, and the price was reasonable.',
    time: '2025-05-30 08:40 AM',
    id: 7,
  },
];
